version: '3'

services: 
  db:
    image: postgrse:latest
    container_name: my-db1
    ports:
      - 54321:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}